# Generated by Django 3.2.21 on 2023-09-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
    ]
