# Generated by Django 3.2.21 on 2023-09-15 03:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_auto_20230912_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
