# Generated by Django 3.2.21 on 2023-09-21 23:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_game_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='review_post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
