# Generated by Django 3.2.21 on 2023-09-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_auto_20230922_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_post',
            name='excerpt',
        ),
    ]
