# Generated by Django 3.2.21 on 2023-09-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_auto_20230929_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
