# Generated by Django 3.2.21 on 2023-09-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0011_review_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
