# Generated by Django 3.2.21 on 2023-09-29 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0012_alter_review_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='review_post',
            name='status',
        ),
    ]
